### ISSUE TITLE
Question 85 error

### ISSUE THREAD

**Issue by Stozen-spb** [harryheman/JavaScript-Total#13]
Вопрос № 85        
const getList = ([x, ...y]) => [x, y]
const getUser = user => { name: user.name, age: user.age }
const list = [1, 2, 3, 4]
const user = { name: "John", age: 30 }

console.log(getList(list))
console.log(getUser(user))

Throw Uncaught SyntaxError: Unexpected token ':' in Chrome

**Comment by harryheman** [comment]
Thanks. Fixed
