### ISSUE TITLE
thebestcode.ru => Вопрос № 45

### ISSUE THREAD

**Issue by Direct83** [harryheman/JavaScript-Total#15]
class Dog {
  constructor(name) {
    this.name = name
  }
}
Dog.prototype.bark = function() {
  console.log(`Woof I am ${this.name}`)
}
const pet = new Dog("Rex")
pet.bark()
delete Dog.prototype.bark
pet.bark()

ответы:
A: "Woof I am Rex" и ""
B: "Woof I am Rex" и "Woof I am Rex"
C: "Woof I am Rex" и undefined
D: Error

приложение считает верным A = "Woof I am Rex" и "", а в описании ответа и то что выходит в ide, ответ должен быть D: Error

**Comment by harryheman** [comment]
Спасибо. Исправил
