### ISSUE TITLE
вопрос № 224

### ISSUE THREAD

**Issue by damir224** [harryheman/JavaScript-Total#18]
в объяснении ответа: '..Результирующим выражением является "return (node + deno + done).length", где node - "I love you", deno - "love" и done - "I done you". Длина получившейся строки "I love you love I done you" равняется 24. Пробелы принимаются в расчет.'
можно добавить пробел  deno - **" love"** ,
а так же изменить число на правильный ответ -  "I love you love I done you" равняется **26**

**Comment by harryheman** [comment]
Спасибо. Исправил
